// MOVIES
export const LOAD_FILMS = 'LOAD_FILMS';
export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';
export const SET_TOTAL_PAGES = 'SET_TOTAL_PAGES';

// UTIL
export const SET_KEYWORD = 'SET_KEYWORD';
export const SET_STYLES = 'SET_STYLES';
export const GET_SIMILAR_FILMS = 'GET_SIMILAR_FILMS';

// LOADING
export const SET_LOADING = 'SET_LOADING';